template_script: /lnet/work/people/stankov/parczech/assets/cpu_job.template
script: /lnet/work/people/stankov/parczech/scripts/align.py

job_name: align
cpus: 8
mem: 24

bash_script_dir: /lnet/work/people/stankov/parczech/slurm-scripts/${job_name}
slurm_logs_dir: /lnet/work/people/stankov/parczech/slurm-logs/${job_name}

recognized_base_path: /lnet/troja/work/people/stankov/parczech4speechmodeling/audio/psp

params:
  output_directory: /lnet/troja/work/people/stankov/parczech4speechmodeling/alignment
  model_names: ["default_whisperlv2_with_numerals", "default_whisperlv2_no_numerals"]
