output_folder: /lnet/work/people/stankov/parczech-data-lindat
links:
  - https://lindat.mff.cuni.cz/repository/xmlui/bitstream/handle/11234/1-5404/audioPSP-2013-Q4.tar?sequence=1&isAllowed=y
  - https://lindat.mff.cuni.cz/repository/xmlui/bitstream/handle/11234/1-5404/audioPSP-2021-Q4.tar?sequence=33&isAllowed=y