debug: True
start_id: 15
inp_base_dir: /lnet/express/work/people/stankov/
out_base_dir: /lnet/troja/work/people/stankov/backup
slurm_logs_dir: /lnet/work/people/stankov/parczech/slurm-logs
template: /lnet/work/people/stankov/parczech/assets/migrate.template
scripts_dir: /lnet/work/people/stankov/parczech/slurm-scripts
directories:
  # - alignment/results/full/words-aligned
  # - alignment/results/full/RELEASE-LAYOUT/parczech-3.0-asr-context.dev
  # - alignment/results/full/RELEASE-LAYOUT/parczech-3.0-asr-context.test
  # - alignment/results/full/RELEASE-LAYOUT/parczech-3.0-asr-other
  # - alignment/results/full/RELEASE-LAYOUT/parczech-3.0-asr-segments.dev
  # - alignment/results/full/RELEASE-LAYOUT/parczech-3.0-asr-segments.test
  # - alignment/results/full/RELEASE-LAYOUT/parczech-3.0-asr-speakers.test
  # - alignment/results/full/RELEASE-LAYOUT/parczech-3.0-asr-speakers.dev
  # - alignment/results/full/RELEASE-LAYOUT/parczech-3.0-asr-train
  # - alignment/new-parczech/baseline/segments_asr
  # - alignment/new-parczech/baseline/punk_asr/
  # - alignment/new-parczech/baseline/align
  # - alignment/new-parczech/baseline/asr
  # - alignment/Thesis
  # - .cache
  # - miniconda3
  - alignment/selecting_test_set
  - alignment/configs
  - alignment/dataframes
  - parczech


  

