template_script: /lnet/work/people/stankov/parczech/assets/gpu_job.template
script: /lnet/work/people/stankov/parczech/scripts/recognize.py

job_name: parcz_rec
cpus: 16
mem: 32
n_gpus: 1

bash_script_dir: /lnet/work/people/stankov/parczech/slurm-scripts/${job_name}
slurm_logs_dir: /lnet/work/people/stankov/parczech/slurm-logs/${job_name}

n_jobs: -1

metadata_df: /lnet/troja/work/people/stankov/parczech4speechmodeling/audioPSP-meta.quarterArchive.tsv

params:
  output_folder: /lnet/troja/work/people/stankov/parczech4speechmodeling
  overwrite_recognized: False
  n_debug: 3
