replacements:
  - original: '%'
    replacement: 'procento'
  - original: '+'
    replacement: 'plus'
  - original: '*'
    replacement: 'krát'
  - original: '@'
    replacement: 'zavináč'
  - original: '°'
    replacement: 'stupňů'
  - original: '€'
    replacement: 'euro'
  - original: '§'
    replacement: 'paragraf'
  - original: '×'
    replacement: 'krát'
  - original: '/'
    replacement: 'děleno'
  - original: '/'
    replacement: 'lomítko'
  - original: '/'
    replacement: 'lomeno'
  - original: '='
    replacement: 'rovná se'
  - original: '\'
    replacement: 'zpětné lomítko'
  
  - original: 'aj'
    replacement: 'a jiné'
  - original: 'aj'
    replacement: 'anglicky'
  - original: 'apod'
    replacement: 'a podobně'
  - original: 'atd'
    replacement: 'a tak dále'
  - original: 'atp'
    replacement: 'a tak podobně'
  - original: 'at'
    replacement: 'a tak'
  - original: 'cca'
    replacement: 'cirka'
  - original: 'ca'
    replacement: 'cirka'
  - original: 'kup'
    replacement: 'kupříkladu'
  - original: 'např'
    replacement: 'například'
  - original: 'ad'
    replacement: 'a další'
  - original: 'tj'
    replacement: 'to jest'
  - original: 'tzn'
    replacement: 'to znamená'
  - original: 'resp'
    replacement: 'respektive'
  - original: 'tzv'
    replacement: 'takzvaný'
  
  - original: 'MHz'
    replacement: 'megahertz'
  - original: 'MWh'
    replacement: 'megawatthodin'
  - original: 'kWh'
    replacement: 'kilowatthodin'
  - original: 'hod'
    replacement: 'hodin'
  - original: 'min'
    replacement: 'minut'
  

  - original: 'km'
    replacement: 'kilometrů'
  - original: 'm'
    replacement: 'metrů'
  - original: 'mm'
    replacement: 'milimetrů'
  - original: 'cm'
    replacement: 'centimetrů'
  
  - original: 'ks'
    replacement: 'kusů'
  
  - original: 'l'
    replacement: 'litrů'
  - original: 'ml'
    replacement: 'mililitrů'

  - original: 'kg'
    replacement: 'kilogramů'
  - original: 'g'
    replacement: 'gramů'
  - original: 'mg'
    replacement: 'miligramů'

  - original: 'tis'
    replacement: 'tisíc'
  - original: 'mil'
    replacement: 'milionů'
  - original: 'mld'
    replacement: 'miliard'
  - original: 'mj'
    replacement: 'mimo jiné'
  - original: 'nar'
    replacement: 'narozen'

  - original: 'Sb'
    replacement: 'Sbírka zákonů'
  - original: 'odst'
    replacement: 'odstavec'
  - original: 'písm'
    replacement: 'písmeno'
  - original: 'č'
    replacement: 'číslo'
  - original: 'čl'
    replacement: 'članek'


  - original: 'I'
    replacement: 'první'
  - original: 'II'
    replacement: 'druhý'
  - original: 'III'
    replacement: 'třetí'
  - original: 'IV'
    replacement: 'čtvrtý'
  - original: 'V'
    replacement: 'pátý'
  - original: 'VI'
    replacement: 'šestý'
  - original: 'VII'
    replacement: 'sedmý'
  - original: 'VIII'
    replacement: 'osmý'
  - original: 'IX'
    replacement: 'devátý'
  - original: 'X'
    replacement: 'desátý'
  - original: 'XI' 
    replacement: 'jedenáctý'
  - original: 'XII'
    replacement: 'dvanáctý'
  - original: 'XIII'
    replacement: 'třináctý'
  - original: 'XIV'
    replacement: 'čtrnáctý'
  - original: 'XV'
    replacement: 'patnáctý'
  - original: 'XVI'
    replacement: 'šestnáctý'
  - original: 'XVII'
    replacement: 'sedmnáctý'
  - original: 'XVIII'
    replacement: 'osmnáctý'
  - original: 'XIX'
    replacement: 'devatenáctý'
  - original: 'XX'
    replacement: 'dvacátý'
  - original: 'XXI'
    replacement: 'dvacátý první'

  - original: 'SMVS'
    replacement: 'Správa Majetku ve Vlastnictví Státu'
  - original: 'NIDV'
    replacement: 'Národní institut pro další vzdělávání'
  - original: 'NDC'
    replacement: 'Nízkoprahové denní centrum'
  - original: 'ČSN'
    replacement: 'Česká státní norma'
  - original: 'RVIS'
    replacement: 'Rada vlády pro informační společnost'
  - original: 'MEŘO'
    replacement: 'Methylester řepkového oleje'
  - original: 'SNB'
    replacement: 'Sbor národní bezpečnosti'
  - original: 'ÚV'
    replacement: 'Ústřední výbor'
  - original: 'FKSP'
    replacement: 'Fond kulturních a sociálních potřeb'
  - original: 'ECHA'
    replacement: 'Evropská agentura pro chemické látky'
  - original: 'SEA'
    replacement: 'Strategické hodnocení vlivů na životní prostředí'
  - original: 'RIV'
    replacement: 'Rejstřík informací o výsledcích' 
  - original: 'CDU'
    replacement: 'Křesťanskodemokratická unie Německa'
  - original: 'ORL'
    replacement: 'Otorinolaryngologie'
  - original: 'BOZP'
    replacement: 'Bezpečnost a ochrana zdraví při práci'
  - original: 'NRF'
    replacement: 'Síly rychlé reakce'
  - original: 'ESIF'
    replacement: 'Evropské strukturální a investiční fondy'
  - original: 'CVVM'
    replacement: 'Centrum pro výzkum veřejného mínění'
  - original: 'MBHS'
    replacement: 'Mezinárodní banka hospodářské spolupráce'
  - original: 'RVHP'
    replacement: 'Rada vzájemné hospodářské pomoci'
  - original: 'ECB'
    replacement: 'Evropská centrální banka'
  - original: 'HPV'
    replacement: 'papilomavirus'
  - original: 'HZS'
    replacement: 'Hasičský záchranný sbor'
  - original: 'DrSc'
    replacement: 'doktor věd'
  - original: 'AIDS'
    replacement: 'syndrom získaného selhání imunity'
  - original: 'VOP'
    replacement: 'Všeobecné obchodní podmínky'
  - original: 'NDR'
    replacement: 'Německá demokratická republika'
  - original: 'ČEB'
    replacement: 'Česká exportní banka'
  - original: 'GRU'
    replacement: 'Hlavní správa rozvědky'
  - original: 'AOS'
    replacement: 'automatický obchodní systém'
  - original: 'UA'
    replacement: 'Ukrajina'
  - original: 'AČR'
    replacement: 'Armáda České republiky'
  - original: 'ČSM'
    replacement: 'Československý svaz mládeže'
  - original: 'NUTS'
    replacement: 'Nomenklatura územních statistických jednotek'
  - original: 'BAT'
    replacement: 'nejlepší dostupné techniky'
  - original: 'SÚJB'
    replacement: 'Státní úřad pro jadernou bezpečnost'
  - original: 'TV'
    replacement: 'televize'
  - original: 'SFŽP'
    replacement: 'Státní fond životního prostředí'
  - original: 'LDN'
    replacement: 'Léčebny dlouhodobě nemocných'
  - original: 'ETCS'
    replacement: 'jednotný evropský vlakový zabezpečovací systém'
  - original: 'ZEVO'
    replacement: 'zařízení pro energetické využití odpadů'
  - original: 'VTÚ'
    replacement: 'Vojenský technický ústav'
  - original: 'ARO'
    replacement: 'Anesteziologické a resuscitační oddělení'
  - original: 'OZP'
    replacement: 'Osobou se zdravotním postižením'
  - original: 'JES'
    replacement: 'Jednotné environmentální stanovisko'
  - original: 'ECDC'
    replacement: 'Evropské středisko pro prevenci a kontrolu nemocí'
  - original: 'MIB'
    replacement: 'Mezinárodní investiční banka'
  - original: 'IKEM'
    replacement: 'Institut klinické a experimentální medicíny'
  - original: 'CBD'
    replacement: 'cannabidiol'
  - original: 'OČR'
    replacement: 'ošetřování člena rodiny'
  - original: 'DTI'
    replacement: 'Debt To Income'
  - original: 'ADIS'
    replacement: 'Automatizovaný daňový informační systém'
  - original: 'MERO'
    replacement: 'Mezinárodní ropovody'
  - original: 'IZIP'
    replacement: 'Elektronická zdravotní knížka'
  - original: 'ČSOB'
    replacement: 'Československá obchodní banka'
  - original: 'KHS'
    replacement: 'Krajská hygienická stanice'
  - original: 'Bc'
    replacement: 'bakalář'
  - original: 'ČIŽP'
    replacement: 'Česká inspekce životního prostředí'
  - original: 'ODA'
    replacement: 'Občanská demokratická aliance'
  - original: 'RRTV'
    replacement: 'Rada pro rozhlasové a televizní vysílání'
  - original: 'JIP'
    replacement: 'Jednotka intenzivní péče'
  - original: 'IRR'
    replacement: 'Vnitřní výnosové procento'
  - original: 'EHS'
    replacement: 'Evropská hospodářská společenství'
  - original: 'LPG'
    replacement: 'zkapalněný ropný plyn'
  - original: 'ČSSZ'
    replacement: 'Česká správa sociálního zabezpečení'
  - original: 'ÚZSI'
    replacement: 'Úřad pro zahraniční styky a informace'
  - original: 'IS'
    replacement: 'informační systém'
  - original: 'plk'
    replacement: 'plukovník'
  - original: 'SFPI'
    replacement: 'Státní fond podpory investic'
  - original: 'BVP'
    replacement: 'Bojové vozidlo pěchoty'
  - original: 'DIČ'
    replacement: 'daňové identifikační číslo'
  - original: 'ČEPS'
    replacement: 'Česká elektroenergetická přenosová soustava'
  - original: 'CNG'
    replacement: 'stlačený zemní plyn'
  - original: 'PSP'
    replacement: 'Poslanecká sněmovna Parlamentu'
  - original: 'LOM'
    replacement: 'Letecké Opravny Malešice'
  - original: 'PhDr'
    replacement: 'doktor filozofie'
  - original: 'MIV'
    replacement: 'Mecahnický invalidní vozík'
  - original: 'IPB'
    replacement: 'Investiční a poštovní banka'
  - original: 'SZPI'
    replacement: 'Státní zemědělská a potravinářská inspekce'
  - original: 'AGRO'
    replacement: 'Fakultu agrobiologie potravinových a přírodních zdrojů'
  - original: 'ISIN'
    replacement: 'Informační systém infekční nemoci'
  - original: 'DEZA'
    replacement: 'DEhtové ZÁvody'
  - original: 'ESA'
    replacement: 'Evropská kosmická agentura'
  - original: 'CT'
    replacement: 'tomografie'
  - original: 'AFD'
    replacement: 'Alternativa pro Německo'
  - original: 'ADH'
    replacement: 'antidiuretický hormon'
  - original: 'ODS'
    replacement: 'Občanská demokratická strana'
  - original: 'ÚS'
    replacement: 'Ústavní soud'
  - original: 'ONIV'
    replacement: 'Odborný národní inspektorát výstavby'
  - original: 'MHD'
    replacement: 'městská hromadná doprava'
  - original: 'SFRB'
    replacement: 'Státní fond rozvoje bydlení'
  - original: 'IČO'
    replacement: 'identifikační číslo osoby'
  - original: 'ČOI'
    replacement: 'Česká obchodní inspekce'
  - original: 'IPVZ'
    replacement: 'Institut postgraduálního vzdělávání ve zdravotnictví'
  - original: 'atp'
    replacement: 'a tak podobně'
  - original: 'RUDu'
    replacement: 'rozpočtové určení daně'
  - original: 'sv'
    replacement: 'svatý'
  - original: 'HIV'
    replacement: 'virus lidské imunodeficience'
  - original: 'EMA'
    replacement: 'Evropská léková agentura'
  - original: 'ZZN'
    replacement: 'Zemědělské zásobování a nákup'
  - original: 'ČVUT'
    replacement: 'České vysoké učení technické'
  - original: 'OPD'
    replacement: 'Operační program Doprava'
  - original: 'KRIT'
    replacement: 'Krizový informační tým'
  - original: 'DVB'
    replacement: 'Digitální televizní vysílání'
  - original: 'DG'
    replacement: 'Generální ředitelství'
  - original: 'DRG'
    replacement: 'Diagnosis Related Group'
  - original: 'LNG'
    replacement: 'Zkapalněný zemní plyn'
  - original: 'SD'
    replacement: 'Svaz dopravy'
  - original: 'CSc'
    replacement: 'kandidát věd'
  - original: 'WHO'
    replacement: 'Světová zdravotnická organizace'
  - original: 'OP'
    replacement: 'Občanská platforma'
  - original: 'CHKO'
    replacement: 'Chráněná krajinná oblast'
  - original: 'SPU'
    replacement: 'specifické poruchy učení'
  - original: 'ZTP'
    replacement: 'zvlášť těžké postižení'
  - original: 'NCOZ'
    replacement: 'Národní centrála proti organizovanému zločinu'
  - original: 'ROP'
    replacement: 'Retinopatie nedonošených dětí'
  - original: 'EIB'
    replacement: 'Evropská investiční banka'
  - original: 'PČR'
    replacement: 'Policie České republiky'
  - original: 'OZE'
    replacement: 'Obnovitelné zdroje energie'
  - original: 'DPČ'
    replacement: 'Dohoda o pracovní činnosti'
  - original: 'NBÚ'
    replacement: 'Národní bezpečnostní úřad'
  - original: 'PVZP'
    replacement: 'pojišťovna VZP'
  - original: 'NZIS'
    replacement: 'Národní zdravotní informační systém'
  - original: 'JŘBU'
    replacement: 'Jednací řízení bez uveřejnění'
  - original: 'EGAP'
    replacement: 'Exportní garanční a pojišťovací společnost'
  - original: 'DAC'
    replacement: 'Digitálně analogový převodník'
  - original: 'AML'
    replacement: 'opatření proti praní špinavých peněz'
  - original: 'AML'
    replacement: 'akutní myeloidní leukémie'
  - original: 'ČSA'
    replacement: 'Československé státní aerolinie'
  - original: 'MŽP'
    replacement: 'Ministerstvo životního prostředí'
  - original: 'OSA'
    replacement: 'Ochranný svaz autorský'
  - original: 'ÚOOZ'
    replacement: 'Útvar pro odhalování organizovaného zločinu'
  - original: 'DPP'
    replacement: 'Dohoda o provedení práce'
  - original: 'DIA'
    replacement: 'Digitální a informační agentura'
  - original: 'ČD'
    replacement: 'České dráhy'
  - original: 'IROP'
    replacement: 'Integrovaný regionální operační program'
  - original: 'NSA'
    replacement: 'Národní bezpečnostní agentura'
  - original: 'JUDr'
    replacement: 'doktor práv'
  - original: 'KSČ'
    replacement: 'Komunistická strana Československa'
  - original: 'STK'
    replacement: 'Státní technická kontrola'
  - original: 'SZIF'
    replacement: 'Státní zemědělský intervenční fond'
  - original: 'NEN'
    replacement: 'Národní elektronický nástroj'
  - original: 'OBSE'
    replacement: 'Organizace pro bezpečnost a spolupráci v Evropě'
  - original: 'FAÚ'
    replacement: 'Finančního analytického útvaru'
  - original: 'ČNB'
    replacement: 'Česká národní banka'
  - original: 'StB'
    replacement: 'Státní bezpečnost'
  - original: 'IZS'
    replacement: 'Integrovaný záchranný systém'
  - original: 'příp'
    replacement: 'případně'
  - original: 'hl'
    replacement: 'hlavní'
  - original: 'ÚZIS'
    replacement: 'Ústav zdravotnických informací a statistiky'
  - original: 'ICT'
    replacement: 'informační a komunikační technologie'
  - original: 'ÚPV'
    replacement: 'Úřad průmyslového vlastnictví'
  - original: 'ORP'
    replacement: 'Obce s rozšířenou působností'
  - original: 'MUDr'
    replacement: 'doktor medicíny'
  - original: 'ČTK'
    replacement: 'Česká tisková kancelář'
  - original: 'PES'
    replacement: 'Protiepidemický systém'
  - original: 'OLAF'
    replacement: 'Evropský úřad pro boj proti podvodům'
  - original: 'dr'
    replacement: 'doktor'
  - original: 'PPP'
    replacement: 'Pedagogicko-psychologická poradna'
  - original: 'RUD'
    replacement: 'rozpočtové určení daně'
  - original: 'SÚKL'
    replacement: 'Státní ústav pro kontrolu léčiv'
  - original: 'prof'
    replacement: 'profesor'
  - original: 'ES'
    replacement: 'Evropská společenství'
  - original: 'ČTÚ'
    replacement: 'Český telekomunikační úřad'
  - original: 'BIS'
    replacement: 'Bezpečnostní informační služba'
  - original: 'PR'
    replacement: 'public relations'
  - original: 'SŽDC'
    replacement: 'Správa železniční dopravní cesty'
  - original: 'MŠMT'
    replacement: 'Ministerstvo školství, mládeže a tělovýchovy'
  - original: 'GIBS'
    replacement: 'Generální inspekce bezpečnostních sborů'
  - original: 'GDPR'
    replacement: 'obecné nařízení o ochraně osobních údajů'
  - original: 'CoV'
    replacement: 'koronavirus'
  - original: 'Mgr'
    replacement: 'magistr'
  - original: 'ČEZu'
    replacement: 'České energetické závody'
  - original: 'ÚOHS'
    replacement: 'Úřad pro ochranu hospodářské soutěže'
  - original: 'ERÚ'
    replacement: 'Energetický regulační úřad'
  - original: 'ČNB'
    replacement: 'Česká národní banka'
  - original: 'ČT'
    replacement: 'Česká televize'
  - original: 'MMR'
    replacement: 'Ministerstvo pro místní rozvoj'
  - original: 'MPO'
    replacement: 'Ministerstvo průmyslu a obchodu'
  - original: 'OECD'
    replacement: 'Organizace pro ekonomickou spolupráci a rozvoj'
  - original: 'SFDI'
    replacement: 'Státní fond dopravní infrastruktury'
  - original: 'VZP'
    replacement: 'Všeobecná zdravotní pojišťovna'
  - original: 'RIA'
    replacement: 'Hodnocení dopadů regulace'
  - original: 'USA'
    replacement: 'Spojené státy americké'
  - original: 'ŘSD'
    replacement: 'Ředitelství silnic a dálnic'
  - original: 'OSVČ'
    replacement: 'osoba samostatně výdělečně činná'
  - original: 'Ing'
    replacement: 'inženýr'
  - original: 'IT'
    replacement: 'informační technologie'
  - original: 'OSN'
    replacement: 'Organizace spojených národů'
  - original: 'MPSV'
    replacement: 'Ministerstvo práce a sociálních věcí'
  - original: 'ČEZ'
    replacement: 'České energetické závody'
  - original: 'EIA'
    replacement: 'Vyhodnocení vlivů na životní prostředí'
  - original: 'NKÚ'
    replacement: 'Nejvyšší kontrolní úřad'
  - original: 'HDP'
    replacement: 'hrubý domácí produkt'
  - original: 'OKD'
    replacement: 'Ostravsko-karvinské doly'
  - original: 'OKD'
    replacement: 'Obvodní kulturní dům'
  - original: 'STAN'
    replacement: 'Starostové a nezávislí'
  - original: 'Kč'
    replacement: 'korun'
  - original: 'KSČM'
    replacement: 'Komunistická strana Čech a Moravy'
  - original: 'ČSSD'
    replacement: 'Česká strana sociálně demokratická'
  - original: 'ČSL'
    replacement: 'Československá strana lidová'
  - original: 'EET'
    replacement: 'Elektronická evidence tržeb'
  - original: 'KDU'
    replacement: 'Křesťanská a demokratická unie'
  - original: 'EU'
    replacement: 'Evropská unie'
  - original: 'DPH'
    replacement: 'daň z přidané hodnoty'
  - original: 'ČR'
    replacement: 'Česká republika'
  - original: 'ČR'
    replacement: 'Česko'
  - original: 'ODS'
    replacement: 'Občanská demokratická strana'
  - original: 'SPD'
    replacement: 'Svoboda a přímá demokracie'
  - original: 'ANO'
    replacement: 'Akce nespokojených občanů'  
  
  
